version: '2'

services:
    db:
        image: mysql
        ports:
            - 3307:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    php:
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:rw,cached
            - ./logs/symfony:/var/www/symfony/app/logs:rw,cached
    nginx:
        build: docker/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - .docker/elk/logstash:/etc/logstash:rw,cached
            - .docker/elk/logstash/patterns:/opt/logstash/patterns:rw,cached
        volumes_from:
            - php
            - nginx
